INSERT INTO "ProcedureType" (id, code, "nameVi", "nameEn", category, "defaultFeeVND", "discountRule", description, "isActive", "createdAt", "updatedAt") VALUES
(gen_random_uuid()::text, 'IMPLANT_SINGLE', 'Cấy ghép implant', 'Implant Placement', 'IMPLANT_PLACEMENT', 3500000, '{"type":"nth_discount","from":2,"feeVND":3000000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'HEALING_ABUTMENT', 'Đặt Healing abutment', 'Healing Abutment', 'HEALING', 300000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ABUTMENT_IMPRESSION', 'Đặt Abutment, lấy dấu', 'Abutment & Impression', 'PROSTHETIC', 300000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'IMPRESSION', 'Lấy dấu', 'Impression', 'PROSTHETIC', 200000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'PROSTHETIC_IMPLANT', 'Gắn phục hình implant đơn', 'Implant Prosthetic Delivery', 'PROSTHETIC', 700000, NULL, 'Lấy dấu + phục hình. Chỉ phục hình: 400.000d/răng', true, NOW(), NOW()),
(gen_random_uuid()::text, 'PROSTHETIC_ONLY', 'Phục hình (không lấy dấu)', 'Prosthetic Only', 'PROSTHETIC', 400000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'EXTRACTION_ATRAUMATIC', 'Nhổ răng không sang chấn', 'Atraumatic Extraction', 'EXTRACTION', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'IMMEDIATE_TEMP', 'Răng tạm tức thì trên implant', 'Immediate Temporary on Implant', 'PROSTHETIC', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'CUSTOM_HEALING', 'Healing cá nhân (tức thì)', 'Custom Healing Abutment', 'HEALING', 700000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'WISDOM_MEDIUM', 'Nhổ răng khôn lệch, ngầm trung bình', 'Wisdom Tooth Extraction (Medium)', 'EXTRACTION', 1500000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'WISDOM_DIFFICULT', 'Nhổ răng khôn ngầm/lệch khó', 'Wisdom Tooth Extraction (Difficult)', 'EXTRACTION', 2000000, '{"type":"range","minVND":2000000,"maxVND":3000000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'BONE_GRAFT', 'Ghép xương', 'Bone Graft', 'BONE_GRAFT', 2000000, '{"type":"tiered","tiers":[{"upTo":1,"feeVND":2000000},{"upTo":2,"additionalVND":1500000},{"from":3,"flatVND":4500000}]}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'EXTRACTION_BONE_GRAFT', 'Nhổ răng + ghép xương', 'Extraction + Bone Graft', 'EXTRACTION', 2000000, '{"type":"nth_discount","from":2,"feeVND":1800000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'SINUS_CLOSED_NO_GRAFT', 'Nâng xoang kín không ghép xương', 'Closed Sinus Lift (no graft)', 'SINUS_LIFT', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'SINUS_CLOSED_GRAFT', 'Nâng xoang kín + ghép xương', 'Closed Sinus Lift + Bone Graft', 'SINUS_LIFT', 4000000, '{"type":"per_side_with_extra","baseFeeVND":4000000,"baseCovers":2,"extraPerToothVND":1200000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'SINUS_OPEN_GRAFT', 'Nâng xoang hở + ghép xương', 'Open Sinus Lift + Bone Graft', 'SINUS_LIFT', 5000000, '{"type":"per_side_with_extra","baseFeeVND":5000000,"baseCovers":2,"extraPerToothVND":1500000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ALL_ON_4', 'All-on-4 (phẫu thuật + phục hình tạm)', 'All-on-4 Surgery + Temp Prosthetic', 'FULL_ARCH', 24000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ALL_ON_5_6', 'All-on-5/6 (phẫu thuật + phục hình tạm)', 'All-on-5/6 Surgery + Temp Prosthetic', 'FULL_ARCH', 30000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ALL_ON_4_PROSTHETIC', 'Phục hình chính thức All-on-4', 'All-on-4 Final Prosthetic', 'FULL_ARCH', 6000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ALL_ON_5_6_PROSTHETIC', 'Phục hình chính thức All-on-5/6', 'All-on-5/6 Final Prosthetic', 'FULL_ARCH', 8000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ZYGOMATIC', 'Implant xương gò má (Zygomatic)', 'Zygomatic Implant', 'COMPLEX_IMPLANT', 15000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'PTERYGOID', 'Implant xương chân bướm (Pterygoid)', 'Pterygoid Implant', 'COMPLEX_IMPLANT', 11000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'REMOVE_OLD_IMPLANT', 'Tháo implant cũ', 'Remove Old Implant', 'IMPLANT_PLACEMENT', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'REMOVE_IMPLANT_GRAFT', 'Tháo implant cũ + ghép xương', 'Remove Implant + Bone Graft', 'IMPLANT_PLACEMENT', 3000000, '{"type":"nth_discount","from":2,"feeVND":2700000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'CROWN_LENGTHENING', 'Cắt nướu / cười hở lợi + mài chỉnh xương', 'Crown Lengthening / Gummy Smile', 'OTHER', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'FULL_ARCH_DENTURE', 'Lấy dấu + phục hình hàm giả trên implant', 'Full Arch Denture on Implant', 'PROSTHETIC', 4000000, NULL, NULL, true, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;
