INSERT INTO "ProcedureType" (id, code, "nameVi", "nameEn", category, "defaultFeeVND", "discountRule", description, "isActive", "createdAt", "updatedAt") VALUES
(gen_random_uuid()::text, 'IMPLANT_SINGLE', 'Cam ghep implant', 'Implant Placement', 'IMPLANT_PLACEMENT', 3500000, '{"type":"nth_discount","from":2,"feeVND":3000000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'HEALING_ABUTMENT', 'Dat Healing abutment', 'Healing Abutment', 'HEALING', 300000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ABUTMENT_IMPRESSION', 'Dat Abutment, lay dau', 'Abutment & Impression', 'PROSTHETIC', 300000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'IMPRESSION', 'Lay dau', 'Impression', 'PROSTHETIC', 200000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'PROSTHETIC_IMPLANT', 'Gan phuc hinh implant don', 'Implant Prosthetic Delivery', 'PROSTHETIC', 700000, NULL, 'Lay dau + phuc hinh. Chi phuc hinh: 400.000d/rang', true, NOW(), NOW()),
(gen_random_uuid()::text, 'PROSTHETIC_ONLY', 'Phuc hinh (khong lay dau)', 'Prosthetic Only', 'PROSTHETIC', 400000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'EXTRACTION_ATRAUMATIC', 'Nho rang khong sang chan', 'Atraumatic Extraction', 'EXTRACTION', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'IMMEDIATE_TEMP', 'Rang tam tuc thi tren implant', 'Immediate Temporary on Implant', 'PROSTHETIC', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'CUSTOM_HEALING', 'Healing ca nhan (tuc thi)', 'Custom Healing Abutment', 'HEALING', 700000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'WISDOM_MEDIUM', 'Nho rang khon lech, ngam trung binh', 'Wisdom Tooth Extraction (Medium)', 'EXTRACTION', 1500000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'WISDOM_DIFFICULT', 'Nho rang khon ngam/lech kho', 'Wisdom Tooth Extraction (Difficult)', 'EXTRACTION', 2000000, '{"type":"range","minVND":2000000,"maxVND":3000000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'BONE_GRAFT', 'Ghep xuong', 'Bone Graft', 'BONE_GRAFT', 2000000, '{"type":"tiered","tiers":[{"upTo":1,"feeVND":2000000},{"upTo":2,"additionalVND":1500000},{"from":3,"flatVND":4500000}]}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'EXTRACTION_BONE_GRAFT', 'Nho rang + ghep xuong', 'Extraction + Bone Graft', 'EXTRACTION', 2000000, '{"type":"nth_discount","from":2,"feeVND":1800000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'SINUS_CLOSED_NO_GRAFT', 'Nang xoang kin khong ghep xuong', 'Closed Sinus Lift (no graft)', 'SINUS_LIFT', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'SINUS_CLOSED_GRAFT', 'Nang xoang kin + ghep xuong', 'Closed Sinus Lift + Bone Graft', 'SINUS_LIFT', 4000000, '{"type":"per_side_with_extra","baseFeeVND":4000000,"baseCovers":2,"extraPerToothVND":1200000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'SINUS_OPEN_GRAFT', 'Nang xoang ho + ghep xuong', 'Open Sinus Lift + Bone Graft', 'SINUS_LIFT', 5000000, '{"type":"per_side_with_extra","baseFeeVND":5000000,"baseCovers":2,"extraPerToothVND":1500000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ALL_ON_4', 'All-on-4 (phau thuat + phuc hinh tam)', 'All-on-4 Surgery + Temp Prosthetic', 'FULL_ARCH', 24000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ALL_ON_5_6', 'All-on-5/6 (phau thuat + phuc hinh tam)', 'All-on-5/6 Surgery + Temp Prosthetic', 'FULL_ARCH', 30000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ALL_ON_4_PROSTHETIC', 'Phuc hinh chinh thuc All-on-4', 'All-on-4 Final Prosthetic', 'FULL_ARCH', 6000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ALL_ON_5_6_PROSTHETIC', 'Phuc hinh chinh thuc All-on-5/6', 'All-on-5/6 Final Prosthetic', 'FULL_ARCH', 8000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'ZYGOMATIC', 'Implant xuong go ma (Zygomatic)', 'Zygomatic Implant', 'COMPLEX_IMPLANT', 15000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'PTERYGOID', 'Implant xuong chan buom (Pterygoid)', 'Pterygoid Implant', 'COMPLEX_IMPLANT', 11000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'REMOVE_OLD_IMPLANT', 'Thao implant cu', 'Remove Old Implant', 'IMPLANT_PLACEMENT', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'REMOVE_IMPLANT_GRAFT', 'Thao implant cu + ghep xuong', 'Remove Implant + Bone Graft', 'IMPLANT_PLACEMENT', 3000000, '{"type":"nth_discount","from":2,"feeVND":2700000}', NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'CROWN_LENGTHENING', 'Cat nuou / cuoi ho loi + mai chinh xuong', 'Crown Lengthening / Gummy Smile', 'OTHER', 1000000, NULL, NULL, true, NOW(), NOW()),
(gen_random_uuid()::text, 'FULL_ARCH_DENTURE', 'Lay dau + phuc hinh ham gia tren implant', 'Full Arch Denture on Implant', 'PROSTHETIC', 4000000, NULL, NULL, true, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;
